import React, { useEffect, useState } from 'react';
import { Archive, RefreshCcw, Save, ShieldCheck, Trash2 } from 'lucide-react';
import type { LabAggregate } from '../../types.js';
import { JsonFieldEditor } from './JsonFieldEditor.js';
import { statusClasses } from './orchestrator-utils.js';

export const LabEditor: React.FC<{ lab: LabAggregate; activeRuntimeCount?: number; disabled?: boolean; canPermanentDelete?: boolean; onSave: (input: Record<string, unknown>) => Promise<unknown>; onReady: () => Promise<unknown>; onArchive: () => Promise<unknown>; onResetRuntimes: () => Promise<unknown>; onPermanentDelete?: () => Promise<unknown> }> = ({ lab, activeRuntimeCount = 0, disabled, canPermanentDelete, onSave, onReady, onArchive, onResetRuntimes, onPermanentDelete }) => {
  const [draft, setDraft] = useState(lab);
  useEffect(() => setDraft(lab), [lab]);
  const save = () => onSave({ expectedRevision: lab.revision, slug: draft.slug, title: draft.title, summary: draft.summary, isInteractive: draft.isInteractive, manifestVersion: draft.manifestVersion, capabilities: draft.capabilities, normalizedState: draft.normalizedState, metadata: draft.metadata, sortOrder: draft.sortOrder });
  return <div className="space-y-4 rounded-xl border border-white/10 bg-black/25 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-mono text-[10px] font-bold uppercase tracking-wider text-[#00d4ff]">Lab aggregate editor</div><p className="mt-1 text-[10px] text-white/35">{lab.domain} → {lab.kind} · canonical revision r{lab.revision}</p></div><span className={`rounded border px-2 py-1 font-mono text-[9px] ${statusClasses(lab.status)}`}>{lab.status}</span></div>
    {activeRuntimeCount > 0 && <div className="flex items-center justify-between gap-3 rounded-lg border border-amber-400/25 bg-amber-400/10 p-3 text-xs text-amber-100"><span>{activeRuntimeCount} active scenario runtime(s) block canonical state changes.</span><button type="button" disabled={disabled} onClick={() => void onResetRuntimes()} className="inline-flex items-center gap-1 rounded border border-amber-200/20 px-2 py-1 font-mono text-[9px] uppercase"><RefreshCcw className="h-3 w-3" />Reset all</button></div>}
    <div className="grid gap-3 md:grid-cols-2"><label className="space-y-1"><span className="text-[10px] text-white/40">Title</span><input value={draft.title} onChange={(event) => setDraft((current) => ({ ...current, title: event.target.value }))} className="w-full rounded-lg border border-white/10 bg-black px-3 py-2 text-xs text-white" /></label><label className="space-y-1"><span className="text-[10px] text-white/40">Slug</span><input value={draft.slug} onChange={(event) => setDraft((current) => ({ ...current, slug: event.target.value }))} className="w-full rounded-lg border border-white/10 bg-black px-3 py-2 font-mono text-xs text-white" /></label><label className="space-y-1 md:col-span-2"><span className="text-[10px] text-white/40">Summary</span><textarea rows={2} value={draft.summary ?? ''} onChange={(event) => setDraft((current) => ({ ...current, summary: event.target.value || null }))} className="w-full rounded-lg border border-white/10 bg-black px-3 py-2 text-xs text-white" /></label><label className="space-y-1"><span className="text-[10px] text-white/40">Capabilities (comma separated)</span><input value={draft.capabilities.join(', ')} onChange={(event) => setDraft((current) => ({ ...current, capabilities: event.target.value.split(',').map((entry) => entry.trim()).filter(Boolean) }))} className="w-full rounded-lg border border-white/10 bg-black px-3 py-2 text-xs text-white" /></label><label className="flex items-end gap-2 pb-2 text-xs text-white/60"><input type="checkbox" checked={draft.isInteractive} onChange={(event) => setDraft((current) => ({ ...current, isInteractive: event.target.checked }))} />Interactive Lab</label></div>
    <JsonFieldEditor label="Normalized state" value={draft.normalizedState} onChange={(value) => setDraft((current) => ({ ...current, normalizedState: value }))} description="Persisted canonical recorded state. This editor never executes commands or provider tools." />
    <JsonFieldEditor label="Lab metadata" value={draft.metadata} onChange={(value) => setDraft((current) => ({ ...current, metadata: value }))} rows={7} />
    <div className="flex flex-wrap gap-2"><button type="button" disabled={disabled} onClick={() => void save()} className="inline-flex items-center gap-2 rounded-lg border border-[#00ff41]/25 bg-[#00ff41]/10 px-3 py-2 font-mono text-[9px] font-bold uppercase text-[#00ff41] disabled:opacity-40"><Save className="h-3.5 w-3.5" />Save r{lab.revision}</button><button type="button" disabled={disabled || lab.status === 'READY'} onClick={() => void onReady()} className="inline-flex items-center gap-2 rounded-lg border border-[#00d4ff]/25 bg-[#00d4ff]/10 px-3 py-2 font-mono text-[9px] font-bold uppercase text-[#00d4ff] disabled:opacity-40"><ShieldCheck className="h-3.5 w-3.5" />Validate & READY</button><button type="button" disabled={disabled || lab.status === 'ARCHIVED'} onClick={() => void onArchive()} className="inline-flex items-center gap-2 rounded-lg border border-red-500/25 bg-red-500/5 px-3 py-2 font-mono text-[9px] font-bold uppercase text-red-200 disabled:opacity-40"><Archive className="h-3.5 w-3.5" />Archive Lab</button>{canPermanentDelete && ['DRAFT', 'ARCHIVED'].includes(lab.status) && onPermanentDelete && <button type="button" disabled={disabled || activeRuntimeCount > 0} onClick={() => void onPermanentDelete()} className="inline-flex items-center gap-2 rounded-lg border border-red-500/40 bg-red-950/30 px-3 py-2 font-mono text-[9px] font-bold uppercase text-red-100 disabled:opacity-30"><Trash2 className="h-3.5 w-3.5" />Permanent delete</button>}</div>
  </div>;
};
