import React from 'react';
import { Eye, TerminalSquare } from 'lucide-react';
import type { OrchestratorProjectPreview } from '../../types.js';
import { statusClasses } from './orchestrator-utils.js';

export const PreviewPanel: React.FC<{ preview: OrchestratorProjectPreview | null }> = ({ preview }) => {
  if (!preview) return <div className="rounded-xl border border-dashed border-white/10 p-8 text-center text-xs text-white/35">Generate a read-only preview. Preview uses the same public mappers, manifest builder, and domain adapters without changing publication status.</div>;
  return <section className="space-y-4 rounded-xl border border-white/10 bg-black/25 p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 font-mono text-[10px] font-bold uppercase tracking-wider text-[#00d4ff]"><Eye className="h-4 w-4" />Exact public-shape preview</div><h3 className="mt-2 text-lg font-bold text-white">{preview.project.title}</h3><p className="mt-1 text-xs text-white/50">{preview.project.summary}</p></div><span className={`rounded border px-2 py-1 font-mono text-[9px] ${statusClasses(preview.projectPublicationStatus)}`}>{preview.projectPublicationStatus} · r{preview.projectRevision}</span></div><div className="grid gap-3 lg:grid-cols-2">{preview.labs.map((entry) => <div key={entry.lab.id} className="rounded-xl border border-white/10 bg-[#111114] p-4"><div className="flex justify-between gap-3"><div><div className="font-mono text-[9px] font-bold uppercase tracking-wider text-[#00d4ff]">{entry.lab.domain} / {entry.lab.kind}</div><div className="mt-1 text-sm font-semibold text-white">{entry.lab.title}</div></div><span className="font-mono text-[9px] text-white/30">r{entry.labRevision}</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-center"><div className="rounded border border-white/10 p-2"><div className="font-mono text-lg text-white">{entry.manifest.inputs.length}</div><div className="text-[8px] text-white/30">INPUTS</div></div><div className="rounded border border-white/10 p-2"><div className="font-mono text-lg text-white">{entry.scenarioSummary.length}</div><div className="text-[8px] text-white/30">SCENARIOS</div></div><div className="rounded border border-white/10 p-2"><div className="font-mono text-lg text-white">{entry.cliContexts.length}</div><div className="text-[8px] text-white/30">CONTEXTS</div></div></div><div className="mt-3 space-y-1">{entry.cliContexts.slice(0, 4).map((context) => <div key={context.contextId} className="flex items-center gap-2 rounded bg-black px-2 py-1.5 font-mono text-[9px] text-[#00ff41]"><TerminalSquare className="h-3 w-3" />{context.prompt}</div>)}</div>{entry.warnings.length > 0 && <div className="mt-3 space-y-1 text-[9px] text-amber-200/70">{entry.warnings.map((warning) => <div key={warning}>{warning}</div>)}</div>}</div>)}</div></section>;
};
