import 'dotenv/config';

import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';

interface CreatedIds {
  category?: string;
  project?: string;
  blog?: string;
  skill?: string;
  certification?: string;
  inquiry?: string;
}

function safeErrorMessage(error: unknown): string {
  const candidate = error instanceof Error ? `${error.name}: ${error.message}` : 'Unknown error';
  const secrets = [
    process.env.DATABASE_URL,
    process.env.JWT_SECRET,
    process.env.ADMIN_PASSWORD,
  ].filter((value): value is string => Boolean(value));

  return secrets.reduce(
    (message, secret) => message.split(secret).join('[REDACTED]'),
    candidate,
  ).replace(/postgres(?:ql)?:\/\/[^@\s]+@/gi, 'postgresql://[REDACTED]@');
}

async function main(): Promise<void> {
  if (!process.env.DATABASE_URL?.trim()) {
    throw new Error('DATABASE_URL is required for the persistence smoke test');
  }

  const [{ createRepositories }, { createContentServices }, { prisma }] = await Promise.all([
    import('../repositories/repository.factory.js'),
    import('../services/content/index.js'),
    import('../lib/prisma.js'),
  ]);

  const repositories = createRepositories();
  const services = createContentServices(repositories);
  const created: CreatedIds = {};
  const cleanupFailures: string[] = [];
  const suffix = randomUUID().replaceAll('-', '');
  const prefix = `content-smoke-${suffix}`;
  const now = new Date().toISOString();
  let runFailure: unknown;

  async function clean(label: keyof CreatedIds, remove: (id: string) => Promise<boolean>): Promise<void> {
    const id = created[label];
    if (!id) return;

    try {
      await remove(id);
    } catch {
      cleanupFailures.push(label);
    }
  }

  try {
    const health = await repositories.checkHealth();
    assert.deepEqual(health, {
      mode: 'prisma',
      ready: true,
      databaseConnected: true,
    });

    const category = await services.categories.create({
      slug: `${prefix}-category`,
      name: 'Content Smoke Category',
      tagline: 'Disposable persistence verification record',
      description: 'Created only by the Content persistence smoke test.',
      icon: 'FlaskConical',
      accentColor: '#06b6d4',
      terminalTheme: 'cyan',
      sortOrder: 900_001,
      isPublished: true,
      domain: 'DEVOPS',
    });
    created.category = category.id;
    assert.equal((await services.categories.getById(category.id)).slug, `${prefix}-category`);

    const updatedCategory = await services.categories.update(category.id, {
      name: 'Content Smoke Category Updated',
    });
    assert.equal(updatedCategory.name, 'Content Smoke Category Updated');

    const project = await services.projects.create({
      title: 'Content Smoke Project',
      slug: `${prefix}-project`,
      summary: 'Disposable project used to verify PostgreSQL CRUD.',
      descriptionMarkdown: 'This record must be removed when the smoke test ends.',
      categoryId: category.id,
      status: 'COMPLETED',
      formatType: 'standard',
      isFeatured: false,
      sortOrder: 900_001,
      devopsStack: ['Content-Smoke'],
      tags: ['content-smoke', suffix],
    });
    created.project = project.id;
    assert.equal((await services.projects.getById(project.id)).slug, `${prefix}-project`);

    const updatedProject = await services.projects.update(project.id, {
      title: 'Content Smoke Project Updated',
    });
    assert.equal(updatedProject.title, 'Content Smoke Project Updated');

    const blog = await services.blogs.create({
      title: 'Content Smoke Blog',
      slug: `${prefix}-blog`,
      excerpt: 'Disposable blog used to verify PostgreSQL CRUD.',
      contentMarkdown: 'This record is generated by the Content persistence smoke test.',
      categoryId: category.id,
      readTimeMinutes: 1,
      tags: ['content-smoke', suffix],
      isPublished: true,
      publishedAt: now,
    });
    created.blog = blog.id;
    assert.equal((await services.blogs.getById(blog.id)).slug, `${prefix}-blog`);

    const updatedBlog = await services.blogs.update(blog.id, {
      title: 'Content Smoke Blog Updated',
    });
    assert.equal(updatedBlog.title, 'Content Smoke Blog Updated');

    const skill = await services.skills.create({
      name: 'Content Smoke Skill',
      level: 'Proficient',
      proficiencyPercent: 50,
      yearsOfExperience: 0,
      categoryId: category.id,
      iconName: 'FlaskConical',
      terminalSnippet: 'content-smoke --verify',
      sortOrder: 900_001,
    });
    created.skill = skill.id;
    assert.equal((await services.skills.getById(skill.id)).name, 'Content Smoke Skill');

    const updatedSkill = await services.skills.update(skill.id, {
      proficiencyPercent: 51,
    });
    assert.equal(updatedSkill.proficiencyPercent, 51);

    const certification = await services.certifications.create({
      title: 'Content Smoke Certification',
      code: 'PH2B-SMOKE',
      issuer: 'Content Regression Harness',
      credentialId: `${prefix}-credential`,
      badgeIcon: 'FlaskConical',
      issueDate: now,
      categoryId: category.id,
      skillsValidated: ['Disposable CRUD verification'],
      syllabusBreakdown: [{ domain: 'Persistence', percentage: 100 }],
      isFeatured: false,
      sortOrder: 900_001,
    });
    created.certification = certification.id;
    assert.equal(
      (await services.certifications.getById(certification.id)).credentialId,
      `${prefix}-credential`,
    );

    const updatedCertification = await services.certifications.update(certification.id, {
      code: 'PH2B-SMOKE-UPDATED',
    });
    assert.equal(updatedCertification.code, 'PH2B-SMOKE-UPDATED');

    const inquiry = await services.inquiries.create({
      name: 'Content Smoke Inquiry',
      email: `content-smoke+${suffix}@example.invalid`,
      subject: 'Disposable persistence verification',
      message: 'This inquiry must be removed when the smoke test ends.',
      category: 'content-smoke',
      ipAddress: '127.0.0.1',
    });
    created.inquiry = inquiry.id;
    assert.equal((await services.inquiries.getById(inquiry.id)).status, 'NEW');

    const updatedInquiry = await services.inquiries.updateStatus(inquiry.id, 'READ');
    assert.equal(updatedInquiry.status, 'READ');

    await services.inquiries.delete(inquiry.id);
    assert.equal(await repositories.inquiries.findById(inquiry.id), null);

    await services.certifications.delete(certification.id);
    assert.equal(await repositories.certifications.findById(certification.id), null);

    await services.skills.delete(skill.id);
    assert.equal(await repositories.skills.findById(skill.id), null);

    await services.blogs.delete(blog.id);
    assert.equal(await repositories.blogs.findById(blog.id), null);

    await services.projects.delete(project.id);
    assert.equal(await repositories.projects.findById(project.id), null);

    await services.categories.delete(category.id);
    assert.equal(await repositories.categories.findById(category.id), null);
  } catch (error) {
    runFailure = error;
  } finally {
    // Repeat deletes in dependency order. Repository deletes are idempotent and
    // cover both partial setup and a failure between a delete and its assertion.
    await clean('inquiry', (id) => repositories.inquiries.delete(id));
    await clean('certification', (id) => repositories.certifications.delete(id));
    await clean('skill', (id) => repositories.skills.delete(id));
    await clean('blog', (id) => repositories.blogs.delete(id));
    await clean('project', (id) => repositories.projects.delete(id));
    await clean('category', (id) => repositories.categories.delete(id));

    try {
      await prisma.$disconnect();
    } catch {
      cleanupFailures.push('database connection');
    }
  }

  if (cleanupFailures.length > 0) {
    const cleanupMessage = `cleanup failed for: ${cleanupFailures.join(', ')}`;
    if (runFailure) {
      throw new AggregateError([runFailure], `Persistence smoke failed and ${cleanupMessage}`);
    }
    throw new Error(`Persistence smoke ${cleanupMessage}`);
  }

  if (runFailure) throw runFailure;
  console.log('Content persistence smoke: PASS');
}

main().catch((error: unknown) => {
  console.error(`Content persistence smoke: FAIL (${safeErrorMessage(error)})`);
  process.exitCode = 1;
});
